### ISSUE TITLE
Copyright for GPS library

### ISSUE THREAD

**Issue by MaJerle** [itu-rover/2016-2017-Sensor-GPS-STM-Codes-#1]
Dear R&D team,

reviewing your code for GPS, it is very clear that it is copy/paste of my work. This would have no issue if you would keep the license as it should be but you did not!

I'm kindly requesting you to do something from the following options:

- Remove library and do your own from skratch
- Use original library
- Use modified library under original license

Best regards,
Tilen

**Comment by hgaren** [comment]
Dear Tilen,
We had a little bit hurry on that time to catch up deadlines of a
competition . So we forgot to put your copyrightings. We are so sorry about
that and when I reach my computer I will add copyrightings immediately.
Again, sorry for this and thank you for your kind message and your works.
Have a good day.

Software member  of ITU Rover Team
Garen Haddeler


29 Haz 2018 Cum ÖÖ 1:09 tarihinde Tilen Majerle <notifications@github.com>
şunu yazdı:
